# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 420)
        MainWindow.setStyleSheet("border: 1px solid #fff;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 16px;\n"
"background-color: rgb(213, 213, 213);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(10, 30, 110, 110))
        self.btn1.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(234, 234, 234);\n"
"border-radius: 0px;")
        self.btn1.setText("")
        self.btn1.setObjectName("btn1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 370, 200, 40))
        self.label.setStyleSheet("font: 12pt \"Yu Gothic UI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(230, 370, 110, 40))
        self.reset.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\";")
        self.reset.setObjectName("reset")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(120, 30, 110, 110))
        self.btn2.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(230, 30, 110, 110))
        self.btn3.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn3.setText("")
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(10, 140, 110, 110))
        self.btn4.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn4.setText("")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(120, 140, 110, 110))
        self.btn5.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn5.setText("")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(230, 140, 110, 110))
        self.btn6.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn6.setText("")
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(10, 250, 110, 110))
        self.btn7.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn7.setText("")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(120, 250, 110, 110))
        self.btn8.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn8.setText("")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(230, 250, 110, 110))
        self.btn9.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius: 0px;\n"
"background-color: rgb(234, 234, 234);")
        self.btn9.setText("")
        self.btn9.setObjectName("btn9")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(310, 4, 31, 23))
        self.btnClose.setStyleSheet("border: 0px solid #fff;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.btnClose.setObjectName("btnClose")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Start!"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.btnClose.setText(_translate("MainWindow", "x"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
